twitch: null
youtube:
  client_secrets_file: credentials/client_secret.json
  thumbnail_enabled: true
  thumbnail_samples: 8
  thumbnail_width: 1080
  title_templates:
  - '{title} | {game}'
  - '{game} | {title}'
  - 'When {title} in {game}...'
  - '{title} ðŸ˜± | {game}'
  - 'This {game} moment is INSANE | {title}'
instagram:
  caption_templates:
  - '{title}'
  - '{title} | {streamer}'
  hashtags:
  - '#gaming'
  - '#twitch'
  - '#clips'
  - '#highlights'
streamers:
- name: TheBurntPeanut
  twitch_id: '472066926'
  youtube_credentials: credentials/theburntpeanut_youtube.json
  facecam:
    x: 0.15
    y: 0.62
    w: 0.18
    h: 0.34
    output_w: 420
  privacy_status: public
  category_id: '20'
pipeline:
  max_clips_per_streamer: 10
  max_clip_duration_seconds: 45
  velocity_weight: 2.0
  clip_lookback_hours: 168
  min_view_count: 50
  age_decay: log
  view_transform: linear
  title_quality_weight: 0.05
  duration_bonus_weight: 0.3
  optimal_duration_min: 10
  optimal_duration_max: 15
  tmp_dir: data/tmp
  db_path: data/clips.db
  log_file: data/pipeline.log
  upload_spacing_hours: 2
  max_uploads_per_window: 3
  analytics_enabled: true
  instagram_enabled: false
  analytics_min_age_hours: 24
  analytics_sync_interval_hours: 24
  analytics_max_videos_per_run: 20
  captions_enabled: true
  force_upload: false
  posting_schedule:
    enabled: true
    timezone: America/Chicago  # CST/CDT
    weekday_windows:
      - start: '11:00'
        end: '14:00'
      - start: '18:00'
        end: '20:00'
    weekend_windows:
      - start: '08:00'
        end: '10:00'
      - start: '16:00'
        end: '18:00'
